pipeline {
    agent {
      kubernetes {
  label 'slave-dev'
            defaultContainer 'jnlp'
           yaml """
             apiVersion: v1
             kind: Pod
             metadata:
               labels: 
                 kube: slave-dev
             spec:
               volumes:
               - name: host-mount
                 hostPath:
                   path: /var/run/docker.sock
               containers:
               - name: jnlp
                 image: imperialplugins/jenkins-inbound-agent-dind
                 tty: true
                 securityContext:
                   privileged: true
                 volumeMounts:
                   - name: host-mount
                     mountPath: /var/run/docker.sock
              
             """
}//end of kubernetes
 }//end of agent
    tools {
        maven 'Maven 3.5.2'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                    apk update
                    apk add openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
                '''
            }
        }

        stage ('Build Application') {
            steps {
                sh 'mvn clean install'
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
		
		stage ('Build Docker Image') {
            steps {
                sh 'mvn k8s:build k8s:resource'
            }
        }
		
		stage ('Kubernetes Deploy') {
            steps {
                sh 'mvn k8s:deploy'
            }
        }
    }
}
